version: '3.8'
services:
  api_service:
    build: .
    container_name: digital
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/digitaldb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123
    labels:
      - com.centurylinklabs.watchtower.enable=true  # Включаем watchtower для этого контейнера
    depends_on:
      - db

  db:
    image: 'postgres:13.1-alpine'
    ports:
      - "5432:5432"
    container_name: db_postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=digitaldb
    volumes:
      - pg:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=artur@asiptsou.by
      - PGADMIN_DEFAULT_PASSWORD=123
    ports:
      - "5050:80"
    depends_on:
      - db

  #Сервис, который опрашивает докер хаб, если появился более новый image,
  #то скачивает новый образ и запускает новый контейнер с этим образом
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_POLL_INTERVAL=120  # Проверять обновления каждые 120 секунд
      - WATCHTOWER_LABEL_ENABLE=true  # Обновлять только контейнеры с меткой com.centurylinklabs.watchtower.enable=true
    restart: unless-stopped

volumes:
  pg:
