name: maven-build
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  checkstyle:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
      - uses: actions/cache@v3
        with:
          path: C:\actions\cache
          key: maven-${{ hashFiles('**/pom.xml')}}
          restore-keys: |
            maven-
      - run: mvn clean install