name: maven-build
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  checkstyle:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
      - uses: actions/cache@v3
        with:
          path: C:\Users\off_8\.m2\repository
          key: maven-${{ runner.os }}-${{ hashFiles('pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-
      - run: mvn clean install